[project]
name = "hybicraft-bot"
version = "0.1.0"
description = "A Discord bot built with pycord that uses a module-system"
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [
    "py-cord>=2.4.0",
    "toml>=0.10.2",
]

[tool.uv]
dev-dependencies = []